// features/editor/config/filters.ts - ENHANCED FILTERS v2

export interface FilterPreset {
  key: string;
  name: string;
  settings: Record<string, number>;
  intensity?: number;
  description?: string;
}

// Profesyonel Apple Photos + Instagram tarzı filtreler
export const APPLE_FILTERS: FilterPreset[] = [
  {
    key: 'original',
    name: 'Orijinal',
    settings: {},
    description: 'Hiçbir filtre uygulanmamış hali',
  },
  {
    key: 'vivid',
    name: 'Canlı',
    settings: {
      product_saturation: 35,
      product_vibrance: 25,
      product_contrast: 20,
      product_clarity: 15,
      product_warmth: 5,
      product_exposure: 5,
      background_saturation: 15,
      background_contrast: 10,
    },
    description: 'Parlak ve canlı renkler',
  },
  {
    key: 'dramatic',
    name: 'Dramatik',
    settings: {
      product_contrast: 45,
      product_highlights: -25,
      product_shadows: 30,
      product_clarity: 25,
      background_vignette: 30,
      background_contrast: 20,
      product_saturation: 15,
      product_exposure: -5,
    },
    description: 'Yüksek kontrast ve drama',
  },
  {
    key: 'mono',
    name: 'Mono',
    settings: {
      product_saturation: -100,
      background_saturation: -100,
      product_contrast: 25,
      background_contrast: 15,
      product_clarity: 20,
      product_highlights: -5,
      product_shadows: 10,
      background_vignette: 15,
    },
    description: 'Siyah beyaz klasik görünüm',
  },
  {
    key: 'vintage',
    name: 'Vintage',
    settings: {
      product_warmth: 40,
      background_warmth: 25,
      product_contrast: -10,
      background_contrast: -15,
      background_vignette: 40,
      product_saturation: -20,
      background_saturation: -30,
      product_shadows: 15,
      product_exposure: -10,
      product_clarity: -5,
    },
    description: 'Eski film görünümü',
  },
  {
    key: 'cool',
    name: 'Soğuk',
    settings: {
      product_warmth: -30,
      background_warmth: -20,
      product_saturation: 10,
      product_highlights: 10,
      product_contrast: 5,
      product_clarity: 5,
      product_brightness: 3,
      background_brightness: 5,
    },
    description: 'Soğuk tonlu, modern görünüm',
  },
  {
    key: 'warm',
    name: 'Sıcak',
    settings: {
      product_warmth: 25,
      background_warmth: 20,
      product_exposure: 5,
      product_shadows: -10,
      product_saturation: 15,
      product_contrast: 5,
      product_vibrance: 10,
      background_saturation: 10,
    },
    description: 'Sıcak ve davetkar tonlar',
  },
  {
    key: 'bright',
    name: 'Parlak',
    settings: {
      product_exposure: 20,
      background_exposure: 15,
      product_highlights: 15,
      product_shadows: -10,
      product_contrast: 10,
      product_clarity: 10,
      product_saturation: 5,
      product_warmth: 5,
      product_brightness: 8,
      background_brightness: 10,
    },
    description: 'Aydınlık ve enerjik',
  },
  {
    key: 'fade',
    name: 'Soluk',
    settings: {
      product_highlights: -30,
      background_highlights: -20,
      product_shadows: 20,
      background_shadows: 15,
      product_contrast: -20,
      background_contrast: -25,
      product_saturation: -15,
      background_saturation: -20,
      product_exposure: 8,
      product_warmth: 5,
      product_clarity: -10,
      background_vignette: 10,
    },
    description: 'Yumuşak, pastel tonlar',
  },
  {
    key: 'cinema',
    name: 'Sinema',
    settings: {
      product_contrast: 30,
      background_contrast: 20,
      product_shadows: 25,
      product_highlights: -15,
      product_warmth: 5,
      background_vignette: 35,
      product_saturation: -5,
      background_saturation: -10,
      product_clarity: 15,
      product_exposure: -5,
    },
    description: 'Sinematik film görünümü',
  },
  {
    key: 'noir',
    name: 'Noir',
    settings: {
      product_saturation: -100,
      background_saturation: -100,
      product_contrast: 40,
      background_contrast: 30,
      product_highlights: -20,
      product_shadows: 35,
      background_vignette: 45,
      product_clarity: 20,
      product_exposure: -8,
      background_exposure: -10,
    },
    description: 'Klasik film noir stili',
  },
  {
    key: 'pastel',
    name: 'Pastel',
    settings: {
      product_exposure: 12,
      background_exposure: 15,
      product_highlights: -20,
      product_shadows: 15,
      background_shadows: 10,
      product_contrast: -15,
      background_contrast: -20,
      product_saturation: -10,
      background_saturation: -15,
      product_warmth: 8,
      product_clarity: -5,
      product_vibrance: -5,
    },
    description: 'Yumuşak pastel renkler',
  },
  {
    key: 'professional',
    name: 'Profesyonel',
    settings: {
      product_contrast: 15,
      product_clarity: 20,
      product_highlights: -10,
      product_shadows: 15,
      product_saturation: 8,
      product_vibrance: 12,
      product_warmth: 3,
      product_exposure: 3,
      background_contrast: 10,
      background_saturation: 5,
    },
    description: 'Dengeli profesyonel görünüm',
  },
  {
    key: 'portrait',
    name: 'Portre',
    settings: {
      product_warmth: 12,
      product_clarity: -3, // Yumuşak cilt
      product_highlights: -8,
      product_shadows: 12,
      product_saturation: 5,
      product_vibrance: 15,
      product_contrast: 8,
      product_brightness: 5,
      background_blur: 15, // Arka planı hafif bulanıklaştır
      background_saturation: -5,
    },
    description: 'Portre fotoğrafları için optimize',
  },
  {
    key: 'landscape',
    name: 'Manzara',
    settings: {
      product_saturation: 20,
      background_saturation: 25,
      product_vibrance: 25,
      background_vibrance: 20,
      product_clarity: 15,
      product_contrast: 12,
      background_contrast: 10,
      product_highlights: -5,
      product_shadows: 8,
      product_warmth: -3,
      product_exposure: 3,
    },
    description: 'Manzara fotoğrafları için',
  },
  {
    key: 'food',
    name: 'Yemek',
    settings: {
      product_warmth: 15,
      product_saturation: 25,
      product_vibrance: 30,
      product_contrast: 12,
      product_clarity: 8,
      product_highlights: -3,
      product_shadows: 8,
      product_brightness: 5,
      background_warmth: 10,
      background_saturation: 15,
      background_blur: 8, // Arka planı hafif bulanıklaştır
    },
    description: 'Yemek fotoğrafları için optimize',
  },
  {
    key: 'instagram_kelvin',
    name: 'Kelvin',
    settings: {
      product_warmth: 35,
      background_warmth: 25,
      product_contrast: -5,
      background_contrast: -10,
      product_saturation: 20,
      background_saturation: 15,
      background_vignette: 25,
      product_exposure: 8,
      product_shadows: 10,
      product_clarity: -5,
    },
    description: 'Instagram Kelvin filtresi',
  },
  {
    key: 'instagram_lark',
    name: 'Lark',
    settings: {
      product_exposure: 15,
      background_exposure: 12,
      product_brightness: 10,
      background_brightness: 8,
      product_contrast: 5,
      product_saturation: -10,
      background_saturation: -15,
      product_warmth: -5,
      product_highlights: 5,
      product_shadows: -5,
    },
    description: 'Instagram Lark filtresi',
  },
  {
    key: 'instagram_juno',
    name: 'Juno',
    settings: {
      product_warmth: 20,
      background_warmth: 15,
      product_saturation: 30,
      background_saturation: 20,
      product_contrast: 15,
      background_contrast: 10,
      product_vibrance: 20,
      product_clarity: 10,
      background_vignette: 15,
    },
    description: 'Instagram Juno filtresi',
  },
  {
    key: 'custom',
    name: 'Özel',
    settings: {},
    description: 'Kullanıcı tarafından özelleştirilmiş ayarlar',
  },
];

export const ALL_FILTERS = APPLE_FILTERS;