// features/editor/config/filters.ts - ENHANCED FILTERS

export interface FilterPreset {
  key: string;
  name: string;
  settings: Record<string, number>;
  intensity?: number;
  description?: string;
}

// Gelişmiş Apple Photos + Professional filtreleri
export const APPLE_FILTERS: FilterPreset[] = [
  {
    key: 'original',
    name: 'Orijinal',
    settings: {},
    description: 'Hiçbir filtre uygulanmamış hali',
  },
  {
    key: 'vivid',
    name: 'Canlı',
    settings: {
      saturation: 40,
      vibrance: 30,
      contrast: 25,
      clarity: 20,
      warmth: 8,
      exposure: 8,
      brightness: 5,
    },
    description: 'Parlak ve canlı renkler',
  },
  {
    key: 'dramatic',
    name: 'Dramatik',
    settings: {
      contrast: 50,
      highlights: -30,
      shadows: 35,
      clarity: 30,
      background_vignette: 25,
      saturation: 20,
      exposure: -8,
      brightness: -5,
    },
    description: 'Yüksek kontrast ve drama',
  },
  {
    key: 'mono',
    name: 'Mono',
    settings: {
      saturation: -100,
      contrast: 30,
      clarity: 25,
      highlights: -8,
      shadows: 15,
      exposure: 8,
      brightness: 5,
    },
    description: 'Siyah beyaz klasik görünüm',
  },
  {
    key: 'vintage',
    name: 'Vintage',
    settings: {
      warmth: 45,
      contrast: -15,
      background_vignette: 35,
      saturation: -25,
      shadows: 20,
      exposure: -12,
      clarity: -8,
      brightness: -8,
    },
    description: 'Eski film görünümü',
  },
  {
    key: 'cool',
    name: 'Soğuk',
    settings: {
      warmth: -35,
      saturation: 15,
      highlights: 12,
      contrast: 8,
      clarity: 8,
      brightness: 5,
      exposure: 3,
    },
    description: 'Soğuk tonlu, modern görünüm',
  },
  {
    key: 'warm',
    name: 'Sıcak',
    settings: {
      warmth: 30,
      exposure: 8,
      shadows: -12,
      saturation: 20,
      contrast: 8,
      brightness: 5,
      vibrance: 15,
    },
    description: 'Sıcak ve davetkar tonlar',
  },
  {
    key: 'bright',
    name: 'Parlak',
    settings: {
      exposure: 25,
      highlights: 20,
      shadows: -15,
      contrast: 15,
      clarity: 15,
      saturation: 8,
      warmth: 8,
      brightness: 12,
    },
    description: 'Aydınlık ve enerjik',
  },
  {
    key: 'fade',
    name: 'Soluk',
    settings: {
      highlights: -35,
      shadows: 25,
      contrast: -25,
      saturation: -20,
      exposure: 12,
      warmth: 8,
      clarity: -12,
      background_vignette: 8,
      brightness: 8,
    },
    description: 'Yumuşak, pastel tonlar',
  },
  {
    key: 'cinema',
    name: 'Sinema',
    settings: {
      contrast: 35,
      shadows: 30,
      highlights: -20,
      warmth: 8,
      background_vignette: 25,
      saturation: -8,
      clarity: 20,
      exposure: -8,
      brightness: -5,
    },
    description: 'Sinematik film görünümü',
  },
  {
    key: 'noir',
    name: 'Noir',
    settings: {
      saturation: -100,
      contrast: 45,
      highlights: -25,
      shadows: 40,
      background_vignette: 30,
      clarity: 25,
      exposure: -10,
      brightness: -8,
    },
    description: 'Klasik film noir stili',
  },
  {
    key: 'pastel',
    name: 'Pastel',
    settings: {
      exposure: 15,
      highlights: -25,
      shadows: 20,
      contrast: -20,
      saturation: -15,
      warmth: 12,
      clarity: -8,
      brightness: 10,
      vibrance: -10,
    },
    description: 'Yumuşak pastel renkler',
  },
  {
    key: 'professional',
    name: 'Profesyonel',
    settings: {
      contrast: 20,
      clarity: 25,
      highlights: -15,
      shadows: 20,
      saturation: 10,
      vibrance: 15,
      warmth: 5,
      exposure: 5,
    },
    description: 'Dengeli profesyonel görünüm',
  },
  {
    key: 'portrait',
    name: 'Portre',
    settings: {
      warmth: 15,
      clarity: -5, // Yumuşak cilt
      highlights: -10,
      shadows: 15,
      saturation: 8,
      vibrance: 20,
      contrast: 10,
      brightness: 8,
    },
    description: 'Portre fotoğrafları için optimize',
  },
  {
    key: 'landscape',
    name: 'Manzara',
    settings: {
      saturation: 25,
      vibrance: 30,
      clarity: 20,
      contrast: 15,
      highlights: -8,
      shadows: 12,
      warmth: -5,
      exposure: 5,
    },
    description: 'Manzara fotoğrafları için',
  },
  {
    key: 'food',
    name: 'Yemek',
    settings: {
      warmth: 20,
      saturation: 30,
      vibrance: 35,
      contrast: 15,
      clarity: 10,
      highlights: -5,
      shadows: 10,
      brightness: 8,
    },
    description: 'Yemek fotoğrafları için optimize',
  },
];

export const ALL_FILTERS = APPLE_FILTERS;